#! /usr/bin/bash


FILE=secrets.lua

if test -f "$FILE"; then
    echo "secrets.lua already exists!"
else

	touch secrets.lua
echo "return {
    widget = {
        email  = {
            address       = '',
            app_password  = ''
        },

        weather = {
            key           = '',
            city_id       = ''
        },

        network = {
            wired_interface = '',
            wireless_interface = ''
        }
    },

    module = {
        lockscreen = {
            fallback_password = 'admin123',
        }
    }
}
" >> secrets.lua

fi

