#!/bin/sh

# place file "cloudflared" into /etc/rc.d/

# PROVIDE: cloudflared
# REQUIRE: cleanvar SERVERS
#
# Options to configure cloudflared via /etc/rc.conf:
#
# cloudflared_enable (bool)     Enable service on boot
#                               Default: NO
#
# cloudflared_conf (str)        Config file to use
#                               Default: /usr/local/etc/cloudflared/config.yml
#
# cloudflared_mode (str)        Mode to run cloudflared as (e.g. 'tunnel', 'tunnel run'
#                               or 'proxy-dns'). Should you use the default, a free
#                               tunnel is set up for you.
#                               Default: "tunnel"

. /etc/rc.subr

name="cloudflared"
rcvar="cloudflared_enable"
logfile="/var/log/cloudflared.log"
pidfile="/var/run/cloudflared.pid"
procname="/usr/local/bin/cloudflared"

load_rc_config $name

: ${cloudflared_enable:="YES"}
: ${cloudflared_conf:="/usr/local/etc/cloudflared/config.yml"}
: ${cloudflared_mode:="tunnel run"}
: ${tunnel_name:="YOURTOKENHERE"}

command="/usr/sbin/daemon"
command_args="-o ${logfile} -p ${pidfile} -f ${procname} ${cloudflared_mode} ${tunnel_name}"

run_rc_command "$1"
